=== TheOutsiderMan/task-3-1-final-project/src/main/java/by/tr/web/kinorating/controller/command/config/commands.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.tr.web.final.task" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="commands">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="command" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="name"/>
              <xs:element type="xs:string" name="class"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== TheOutsiderMan/task-3-1-final-project/src/main/java/by/tr/web/kinorating/controller/command/config/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<commands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.tr.web.final.task" xsi:schemaLocation="http://www.tr.web.final.task commands.xsd">
	<command>
		<name>search</name>
		<class>by.tr.web.task_3_1.controller.command.impl.SearchImpl</class>
	</command>
	<command>
		<name>authentication</name>
		<class>by.tr.web.task_3_1.controller.command.impl.AuthenticationImpl</class>
	</command>
	<command>
		<name>registration</name>
		<class>by.tr.web.task_3_1.controller.command.impl.RegistrationImpl</class>
	</command>
	<command>
		<name>change_language</name>
		<class>by.tr.web.task_3_1.controller.command.impl.LanguageTogglerImpl</class>
	</command>
	<command>
		<name>log_off</name>
		<class>by.tr.web.task_3_1.controller.command.impl.LogOffImpl</class>
	</command>
	<command>
		<name>init_view</name>
		<class>by.tr.web.task_3_1.controller.command.impl.PageViewInitialzeImpl</class>
	</command>
</commands>

=== TheOutsiderMan/task-3-1-final-project/src/main/java/by/tr/web/task_3_1/controller/command/conf/commands.xml
<?xml version="1.0" encoding="UTF-8"?>
<commands xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xmlns="http://www.tr.web.final.task"
		xsi:schemaLocation="http://www.tr.web.final.task commands.xsd">
	<command>
		<name>SEARCH</name>
		<class>by.tr.web.task_3_1.controller.command.impl.SearchImpl</class>
	</command>
	<command>
		<name>AUTHENTICATION</name>
		<class>by.tr.web.task_3_1.controller.command.impl.AuthenticationImpl</class>
	</command>
	<command>
		<name>REGISTRATION</name>
		<class>by.tr.web.task_3_1.controller.command.impl.RegistrationImpl</class>
	</command>
	<command>
		<name>CHANGE_LANGUAGE</name>
		<class>by.tr.web.task_3_1.controller.command.impl.changeLanguageImpl</class>
	</command>
</commands>
